@echo off 
echo Compiling threebody.c...
gcc threebody.c -o threebody.exe -lm

echo Running threebody.exe...
threebody.exe

echo Generating animation...
python animate.py

echo Opening animation in browser...
start simulation.html
